/*
Even Fibonacci numbers
   
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let fibSeq = [1, 2]
let newElement = 2
// Make Fibonacci's up to 4x10^6
while( newElement < 4000000 ){
    newElement = fibSeq[ fibSeq.length-1 ] + fibSeq[ fibSeq.length-2 ]
    fibSeq.push( newElement )
}
// Get even numbers
let sum = fibSeq.filter( item => item%2===0 )
// Get the sum
console.log( sum.reduce( function(a, b){ return a + b }) )